# .github/workflows/build-and-push.yml
name: Build and Push on Tag

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      docker_registry:
        required: true
        type: string
      docker_repository:
        required: true
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ inputs.app_name }}
      DOCKER_REGISTRY: ${{ inputs.docker_registry }}
      DOCKER_REPOSITORY: ${{ inputs.docker_repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set VERSION without 'v' prefix
        run: |
          RAW_TAG=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$RAW_TAG" >> $GITHUB_ENV

      - name: Set IS_STABLE
        run: |
          if [[ "${VERSION}" == *"dev"* || "${VERSION}" == *"alpha"* || "${VERSION}" == *"beta"* || "${VERSION}" == *"rc"* ]]; then
            echo "IS_STABLE=false" >> $GITHUB_ENV
          else
            echo "IS_STABLE=true" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Docker build and push (non-stable)
        uses: docker/build-push-action@v6
        if: env.IS_STABLE == 'false'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}/${{ env.APP_NAME }}:${{ env.VERSION }}
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}/${{ env.APP_NAME }}:latest
          cache-to: type=inline

      - name: Docker build and push (stable)
        uses: docker/build-push-action@v6
        if: env.IS_STABLE == 'true'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}/${{ env.APP_NAME }}:${{ env.VERSION }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}/${{ env.APP_NAME }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}/${{ env.APP_NAME }}:latest
          cache-to: type=inline

      - name: Logout from Docker Registry
        run: docker logout ${{ env.DOCKER_REGISTRY }}
        if: always()
